version: 0.2
phases:
  build:
    commands:
      - echo starting build
      - mvn clean package
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/spring-aws-storage-service-example.jar
  discard-paths: yes